</> YAML
title: Ibukun Olusunmade -
Data Analytics Projects
logo: assets/img/logo.png
description: A data analyst with over three years experience highly skilled in data analytics tools such as Excel, SQL, Power BI and many more, specialising in leveraging data insights for business and organisation decisions.
#show_downloads: true
#google_analytics:
#theme: jekyll
theme: minima
